export enum EntityType {
    expertWorkingGroup = 1,
    expertPerson = 2,
    certificate = 4,
    rfp = 5,
    teamMember = 6,
    proposal = 7,
    najaExpertsSession = 8,
    user = 9,
    compilationContract = 10,
    basicValue = 11,
    person = 12,
    orgUnit = 13,
    contractSetting = 14,
    policySet = 15,
    baseTheory = 19,
    supervisor = 22,
    supervisionContract = 20,
    targetSpecification = 21,
    sessionPlanning = 23
}
