export enum WorkflowStep {
    Create = 1,
    Check = 2,
    Edit = 3,
    RegisterCertificate = 4,
    RegisterRFP = 5,
    SpecializedTeam = 6,
    Proposal = 7,
    CheckProposal = 8,
    BaseTheory = 9,
    DocumentReviewAgenda = 10,
    AddSupervision = 11,
    CompilationContract = 12,
    SupervisionContract = 13,
    Prepayment = 14,
    Workshop = 15,
    TargetSpecification = 16,
    SessionPlanning = 17,
    HoldingDraftMeetings = 18,
    RegisterRegulationDraft = 19,
}
